name: Generate Pacman Movement
on:
  workflow_dispatch:
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-pacman.svg?color_snake=yellow&color_dots=blue&color_empty=black
            dist/github-contribution-grid-pacman.gif?color_snake=yellow&color_dots=blue&color_empty=black
      - name: ensure the generated file exists
        run: |
          ls dist
          test -f dist/github-contribution-grid-pacman.svg
          test -f dist/github-contribution-grid-pacman.gif
      - name: push pacman animations to the output branch
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          target_branch: manual-run-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
